name: Upload Artifact

on:
  workflow_call:
    inputs:
     env: 
      default: "s"
      required:  true
      type: string
      description: ''

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Artifact
        run: echo "Hello, World!" > ./hello/hello.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: hello/hello.txt
