name: Scheduled Job with Bash

on:
  # push:
  #   branches:
  #     - main
 workflow_call:
  inputs:
      webhook-url:
        description: "webhook secret url"
        type: string
        required: true

jobs:
  cron_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Test Script
        id: run_test
        run: |
          echo "Running a test script..."
          # Simulate a test command here (e.g., run unit tests)
          if [[ 200000 -gt 20000 ]]; then
            echo "Test passed!"
            exit 0
          else
            echo "Test failed!"
            exit 1
          fi

      - name: Notify slack
        if:  ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
         SLACK_COLOR: ${{ steps.run_test.conclusion == 'success' && '00FF00' || 'FF0000' }} # or a specific color like 'good' or '#ff00ff'
         SLACK_MESSAGE: 'Post Content :rocket:'
         SLACK_TITLE: hello
        # SLACK_USERNAME: rtCamp
         SLACK_WEBHOOK: ${{ inputs.webhook-url }}
         # SLACK_WEBHOOK: "https://hooks.slack.com/services/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" 
