name: Scheduled Job with Bash
on:
  schedule:
    - cron: '30 7 13-20 * 1'  # Runs at 5:30 AM UTC on January 10th
  push:
  
jobs:
 cron_check:
    runs-on: ubuntu-latest
    outputs: 
      is_first_monday: ${{ steps.check_first_monday.outputs.is_first_monday }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if it’s the first Monday
        id: check_first_monday
        run: |
          DAY_OF_MONTH=$(date +'%d')
          if [ "$DAY_OF_MONTH" -le 13 ]; then
            echo "This is the third Monday of the month."
            echo "is_first_monday=true" >> $GITHUB_OUTPUT
            
          else
            echo "Not the first Monday. Skipping."
            echo "is_first_monday=false" >> $GITHUB_OUTPUT
            # exit 0
          fi
        
 deployment: 
        name: trigger job
        needs: ["cron_check"]
        if: ${{ needs.cron_check.outputs.is_first_monday == 'true' }}
        runs-on: ubuntu-latest
        steps:
          - name : Deploy test
            run:  echo hello


        


