name: Scheduled Job with Bash
on:
  schedule:
    - cron: '30 7 13-20 * 1'  # Runs at 5:30 AM UTC on January 10th
  push:
  
jobs:
  run_bash_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if it’s the first Monday
        id: check_first_monday
        run: |
          DAY_OF_MONTH=$(date +'%d')
          if [ "$DAY_OF_MONTH" -le 13 ]; then
            echo "This is the first Monday of the month."
            echo "is_first_monday=true" >> $GITHUB_OUTPUT
          else
            echo "Not the first Monday. Skipping."
            echo "is_first_monday=false" >> $GITHUB_OUTPUT
            # exit 0
          fi
        
      - name: trigger job
        if: ${{ steps.output.check_first_monday.is_first_monday == true }}
        uses: ./.github/actions/job@main


        


