name: Scheduled Job with Bash

on:
  push:
    branches:
      - main

jobs:
  cron_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Test Script
        id: run_test
        run: |
          echo "Running a test script..."
          # Simulate a test command here (e.g., run unit tests)
          if [[ 20000000 -gt 20000 ]]; then
            echo "Test passed!"
            exit 0
          else
            echo "Test failed!"
            exit 1
          fi

      - name: Output Status with Color
        if: ${{ always() }}
        run: |
          if [[ ${{ steps.run_test.conclusion }} = 'success' ]]; then
          echo -e "\033[32m✅ Tests Passed Successfully!\033[0m"
          else
           echo -e "\033[31m❌ Tests Failed!\033[0m"
          fi
