name: Scheduled Job with Bash

on:
  schedule:
    - cron: '30 23 10-17 * 4'  # Runs at 5:30 AM UTC on January 10th
  push:
  
jobs:
  run_bash_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Bash script
        run: |
          echo "This job is triggered by a cron schedule"
