name: Scheduled Job with Bash
on:
  push:
    branches:
      - main
  
jobs:
 cron_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Test Script
        id: run_test
        run: |
          echo "Running a test script..."
          # Simulate a test command here (e.g., run unit tests)
          if [[ 200000 -gt 20000 ]]; then
            echo "Test passed!"
            exit 0
          else
            echo "Test failed!"
            exit 1
          fi

      - name: Output on Success
        if: ${{ success() }}
        run: echo -e "\033[32m✅ Tests Passed Successfully!\033[0m"

      - name: Output on Failure
        if: ${{ failure() }}
        run: echo -e "\033[31m❌ Tests Failed!\033[0m"


        


