name: test
on:
 push:
    branches: ["main"]

  # workflow_call:
  #   inputs:
  #     github_pat:
  #       description: 'aws service'
  #       type: string
  #       required: true
  #     task_definition:
  #       type: string
  #       description: 'aws task'
  #       required: true
  #     cluster:
  #       description: 'aws cluster'
  #       type: string
  #       required: true

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read  
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: env
      - name: secrets
        env:
         MY_VAL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN  }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            q.join(q)
          print(q)
 
        shell: python
  #     - uses: actions/checkout@v4
  #     - name: create file 
  #       run: |
  #         touch hello.txt 
  #         echo "hello world!" > ${{ github.workspace }}/hello.txt 
  #     - name: ls
  #       run: ls ${{ github.workspace }}
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: ["job1"]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: ls
  #       run: ls ${{ github.workspace }}
           
