name: test
on:
 push:
   push:
    branches: ["main"]

  # workflow_call:
  #   inputs:
  #     github_pat:
  #       description: 'aws service'
  #       type: string
  #       required: true
  #     task_definition:
  #       type: string
  #       description: 'aws task'
  #       required: true
  #     cluster:
  #       description: 'aws cluster'
  #       type: string
  #       required: true

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: $RUNNER_TEMP
        run: ls $RUNNER_TEMP
      - name: runnertemp
        run: ls ${{ runner.temp }}
  
       
           
