name: test
on:
  workflow_call:
    inputs:
      github_pat:
        description: 'aws service'
        type: string
        required: true
      task_definition:
        type: string
        description: 'aws task'
        required: true
      cluster:
        description: 'aws cluster'
        type: string
        required: true

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume:  arn:aws:iam::637423372838:role/aravind15b_oidc
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Provide a self-hosted runner to execute this job
        uses: PasseiDireto/gh-runner-task-action@v2.1.2
        with:
          github_pat: ${{ inputs.github_pat }}
          cluster: ${{ inputs.cluster }}
          
  actual-job:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run a sample command
        run: echo hello
